fieldLayouts:
  706b4658-fc90-4344-bd0d-0f66db9a1173:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: documentsVolume
hasUrls: true
name: Documents
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET_DOCS
  bucketSelectionMode: manual
  cfDistributionId: $S3_DOCS_DIST_ID
  cfPrefix: ''
  expires: '1 years'
  keyId: $S3_USER_ID
  makeUploadsPublic: ''
  region: $S3_BUCKET_REGION
  secret: $S3_USER_SECRET
  storageClass: ''
  subfolder: $S3_BUCKET_SUBFOLDER
sortOrder: 1
type: craft\awss3\Volume
url: $S3_DOCS_URL
