contentColumnType: string(640)
fieldGroup: a7870a18-8ec8-42bd-bb94-ea232c8eb066 # SEO
handle: seoDescription
instructions: ''
name: 'Description SEO'
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
