columnSuffix: null
contentColumnType: string(640)
handle: seoDescription
instructions: null
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
