columnSuffix: null
contentColumnType: string
fieldGroup: a7870a18-8ec8-42bd-bb94-ea232c8eb066 # SEO
handle: seoOgImage
instructions: 'Format paysage - Image utilisée pour les tags Open Graph'
name: 'Image OG pour SEO'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  defaultUploadLocationSubpath: /seo
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  singleUploadLocationSubpath: /seo
  source: null
  sources:
    - 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
