columnSuffix: null
contentColumnType: string
handle: seoOgImage
instructions: 'Recommend size is 1200 pixels by 630 pixels'
name: 'SEO Open Graph Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  defaultUploadLocationSubpath: /seo
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  restrictedLocationSubpath: /seo
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:00548086-7b2f-44f0-a0e4-c9d91fcaae9e' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
