dateModified: 1647620944
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    9b18697d-2ce6-492b-b628-1a649bb22eaa: 'Image OG pour SEO' # Image OG pour SEO
    228f18ac-b71c-4021-8f66-0d34f29a880f: 'SEO global' # SEO global
    a7870a18-8ec8-42bd-bb94-ea232c8eb066: SEO # SEO
    c1436119-37a0-4b5b-9538-52c47b611fd2: $SITE_GROUP # $SITE_GROUP
    d3974314-8390-48bd-af85-f938616558be: 'Description SEO' # Description SEO
    fc2cb4bb-e016-46f9-a830-653496da88d7: Français # Français
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
system:
  edition: solo
  live: $SYSTEM_STATUS
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: America/New_York
