dateModified: 1603892679
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
system:
  edition: solo
  live: true
  name: Overdog
  schemaVersion: 3.5.13
  timeZone: America/New_York
