enableVersioning: false
handle: homeSingle
name: Accueil
propagationMethod: all
siteSettings:
  fc2cb4bb-e016-46f9-a830-653496da88d7:
    enabledByDefault: true
    hasUrls: true
    template: _sections/singles/home/index
    uriFormat: __home__
type: single
