defaultPlacement: end
enableVersioning: false
entryTypes:
  - 0499bd9f-6aa1-4590-9c16-e86191e0a2b8 # Home
handle: singleHome
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fc2cb4bb-e016-46f9-a830-653496da88d7: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/single/home/index
    uriFormat: __home__
type: single
